# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sample-app-with-remix"
client_id = "4084269aaf861eccbbfbe41011f59bef"
application_url = "https://paraguay-pick-hopefully-commissions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://paraguay-pick-hopefully-commissions.trycloudflare.com/auth/callback",
  "https://paraguay-pick-hopefully-commissions.trycloudflare.com/auth/shopify/callback",
  "https://paraguay-pick-hopefully-commissions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "plus-partner-enablement-camp.myshopify.com"
